FROM ubuntu:vivid

# vivid = 15.04
## or import it as: docker import http://cdimage.ubuntu.com/ubuntu-core/daily/current/vivid-core-amd64.tar.gz


ADD setuptools-pip.sh /setuptools-pip.sh
RUN (bash -x setuptools-pip.sh ; rm setuptools-pip.sh )



