FROM ubuntu:artful

# artful = 17.10
## or import it as: docker import http://cdimage.ubuntu.com/ubuntu-core/daily/current/artful-core-amd64.tar.gz 


ADD setup.sh /setup.sh
RUN (bash -x setup.sh ; rm setup.sh )



